[discord]
  guild = "154649154172223488"
  channel = "248880043294588929"
  token = "MjQ4ODMyNTI0NzA3NDMwNDAw.C5NZBQ.fG5QVSUjTGun97CTah69jm1CtiQ" # Token bot
  status = "jRock Music"
  url = "http://audio.misproductions.com/japan128k"
  #url = "http://radio.animenexus.mx:8102"

[youtube]
  token = "AIzaSyAjg75iAJbQklaYk97ftgFrizjbo82LK5w"
