[discord]
  guild = "154649154172223488"
  channel = "248880043294588929"
  token = "MjA4NzkxNDU4NDc0MzYwODMy.CrRDlw.oOf6gWkERpCJ73h07tarIHzH634" # Token bot
  status = "jRock Music"
  url = "http://audio.misproductions.com/japan128k"
  #url = "http://radio.animenexus.mx:8102"
